import { CountryCode } from './types';

// Helper function to convert country names to codes
export function getCountryCode(countryName: string): CountryCode | undefined {
  const countryMapping: Record<CountryCode, string[]> = {
    'AD': ["andorra"],
    'AE': ["united arab emirates", "uae"],
    'AF': ["afghanistan"],
    'AG': ["antigua and barbuda", "antigua"],
    'AI': ["anguilla"],
    'AL': ["albania"],
    'AM': ["armenia"],
    'AO': ["angola"],
    'AQ': ["antarctica"],
    'AR': ["argentina"],
    'AS': ["american samoa"],
    'AT': ["austria"],
    'AU': ["australia"],
    'AW': ["aruba"],
    'AX': ["aland", "åland"],
    'AZ': ["azerbaijan"],
    'BA': ["bosnia and herzegovina", "bosnia"],
    'BB': ["barbados"],
    'BD': ["bangladesh"],
    'BE': ["belgium"],
    'BF': ["burkina faso"],
    'BG': ["bulgaria"],
    'BH': ["bahrain"],
    'BI': ["burundi"],
    'BJ': ["benin"],
    'BL': ["saint barthelemy", "st barthelemy"],
    'BM': ["bermuda"],
    'BN': ["brunei"],
    'BO': ["bolivia"],
    'BR': ["brazil"],
    'BS': ["bahamas", "the bahamas"],
    'BT': ["bhutan"],
    'BW': ["botswana"],
    'BY': ["belarus"],
    'BZ': ["belize"],
    'CA': ["canada"],
    'CD': ["democratic republic of the congo", "dr congo", "drc"],
    'CF': ["central african republic"],
    'CG': ["republic of the congo", "congo"],
    'CH': ["switzerland"],
    'CI': ["ivory coast", "cote d'ivoire"],
    'CK': ["cook islands"],
    'CL': ["chile"],
    'CM': ["cameroon"],
    'CN': ["china"],
    'CO': ["colombia"],
    'CR': ["costa rica"],
    'CU': ["cuba"],
    'CV': ["cabo verde", "cape verde"],
    'CW': ["curacao", "curaçao"],
    'CY': ["cyprus"],
    'CZ': ["czech republic", "czechia"],
    'DE': ["germany", "deutschland"],
    'DJ': ["djibouti"],
    'DK': ["denmark"],
    'DM': ["dominica"],
    'DO': ["dominican republic"],
    'DZ': ["algeria"],
    'EC': ["ecuador"],
    'EE': ["estonia"],
    'EG': ["egypt"],
    'EH': ["western sahara"],
    'ER': ["eritrea"],
    'ES': ["spain", "españa"],
    'ET': ["ethiopia"],
    'FI': ["finland"],
    'FJ': ["fiji"],
    'FK': ["falkland islands"],
    'FM': ["micronesia"],
    'FO': ["faroe islands"],
    'GA': ["gabon"],
    'GB': ["united kingdom", "uk", "great britain"],
    'GD': ["grenada"],
    'GE': ["georgia"],
    'GG': ["guernsey"],
    'GH': ["ghana"],
    'GI': ["gibraltar"],
    'GL': ["greenland"],
    'GM': ["gambia", "the gambia"],
    'GN': ["guinea"],
    'GQ': ["equatorial guinea"],
    'GR': ["greece"],
    'GS': ["south georgia and the south sandwich islands"],
    'GT': ["guatemala"],
    'GU': ["guam"],
    'GW': ["guinea-bissau"],
    'GY': ["guyana"],
    'HK': ["hong kong"],
    'HM': ["heard island and mcdonald islands"],
    'HN': ["honduras"],
    'HR': ["croatia"],
    'HT': ["haiti"],
    'HU': ["hungary"],
    'ID': ["indonesia"],
    'IE': ["ireland"],
    'IL': ["israel"],
    'IM': ["isle of man"],
    'IN': ["india"],
    'IO': ["british indian ocean territory"],
    'IQ': ["iraq"],
    'IR': ["iran"],
    'IS': ["iceland"],
    'IT': ["italy"],
    'JE': ["jersey"],
    'JM': ["jamaica"],
    'JO': ["jordan"],
    'JP': ["japan"],
    'KE': ["kenya"],
    'KG': ["kyrgyzstan"],
    'KH': ["cambodia"],
    'KI': ["kiribati"],
    'KM': ["comoros"],
    'KN': ["saint kitts and nevis", "st kitts"],
    'KP': ["north korea", "dprk"],
    'KR': ["south korea", "korea"],
    'KW': ["kuwait"],
    'KY': ["cayman islands"],
    'KZ': ["kazakhstan"],
    'LA': ["laos"],
    'LB': ["lebanon"],
    'LC': ["saint lucia", "st lucia"],
    'LI': ["liechtenstein"],
    'LK': ["sri lanka"],
    'LR': ["liberia"],
    'LS': ["lesotho"],
    'LT': ["lithuania"],
    'LU': ["luxembourg"],
    'LV': ["latvia"],
    'LY': ["libya"],
    'MA': ["morocco"],
    'MC': ["monaco"],
    'MD': ["moldova"],
    'ME': ["montenegro"],
    'MF': ["saint martin", "st martin"],
    'MG': ["madagascar"],
    'MH': ["marshall islands"],
    'MK': ["north macedonia", "macedonia"],
    'ML': ["mali"],
    'MM': ["myanmar", "burma"],
    'MN': ["mongolia"],
    'MO': ["macao", "macau"],
    'MP': ["northern mariana islands"],
    'MR': ["mauritania"],
    'MS': ["montserrat"],
    'MT': ["malta"],
    'MU': ["mauritius"],
    'MV': ["maldives"],
    'MW': ["malawi"],
    'MX': ["mexico"],
    'MY': ["malaysia"],
    'MZ': ["mozambique"],
    'NA': ["namibia"],
    'NC': ["new caledonia"],
    'NE': ["niger"],
    'NF': ["norfolk island"],
    'NG': ["nigeria"],
    'NI': ["nicaragua"],
    'NL': ["netherlands"],
    'NP': ["nepal"],
    'NR': ["nauru"],
    'NU': ["niue"],
    'NZ': ["new zealand"],
    'OM': ["oman"],
    'PA': ["panama"],
    'PE': ["peru"],
    'PF': ["french polynesia"],
    'PG': ["papua new guinea"],
    'PH': ["philippines"],
    'PK': ["pakistan"],
    'PL': ["poland"],
    'PM': ["saint pierre and miquelon"],
    'PN': ["pitcairn"],
    'PR': ["puerto rico"],
    'PS': ["palestine"],
    'PT': ["portugal"],
    'PW': ["palau"],
    'PY': ["paraguay"],
    'QA': ["qatar"],
    'RO': ["romania"],
    'RS': ["serbia"],
    'RU': ["russia", "russian federation"],
    'RW': ["rwanda"],
    'SA': ["saudi arabia"],
    'SB': ["solomon islands"],
    'SC': ["seychelles"],
    'SD': ["sudan"],
    'SE': ["sweden"],
    'SG': ["singapore"],
    'SH': ["saint helena"],
    'SI': ["slovenia"],
    'SK': ["slovakia"],
    'SL': ["sierra leone"],
    'SM': ["san marino"],
    'SN': ["senegal"],
    'SO': ["somalia"],
    'SR': ["suriname"],
    'SS': ["south sudan"],
    'ST': ["sao tome and principe"],
    'SV': ["el salvador"],
    'SX': ["sint maarten"],
    'SY': ["syria"],
    'SZ': ["eswatini", "swaziland"],
    'TC': ["turks and caicos islands"],
    'TD': ["chad"],
    'TF': ["french southern territories"],
    'TG': ["togo"],
    'TH': ["thailand"],
    'TJ': ["tajikistan"],
    'TL': ["timor-leste", "east timor"],
    'TM': ["turkmenistan"],
    'TN': ["tunisia"],
    'TO': ["tonga"],
    'TR': ["turkey", "türkiye"],
    'TT': ["trinidad and tobago", "trinidad"],
    'TV': ["tuvalu"],
    'TZ': ["tanzania"],
    'UA': ["ukraine"],
    'UG': ["uganda"],
    'UM': ["united states minor outlying islands"],
    'US': ["united states", "usa", "united states of america"],
    'UY': ["uruguay"],
    'UZ': ["uzbekistan"],
    'VA': ["vatican city", "holy see"],
    'VC': ["saint vincent and the grenadines", "st vincent"],
    'VE': ["venezuela"],
    'VG': ["british virgin islands"],
    'VI': ["us virgin islands"],
    'VN': ["vietnam", "viet nam"],
    'VU': ["vanuatu"],
    'WF': ["wallis and futuna"],
    'WS': ["samoa"],
    'YE': ["yemen"],
    'ZA': ["south africa"],
    'ZM': ["zambia"],
    'ZW': ["zimbabwe"]
  };

  const normalizedCountryName = countryName
    .toLowerCase()
    .replace(/[.,]/g, '')
    .replace(/\s*(the|republic of)\s*/g, '')
    .trim();

  return (
    Object.entries(countryMapping)
          .find(([, names]) => names.includes(normalizedCountryName))?.[0] 
  ) as CountryCode | undefined;
}
